server:
  port: 4000
  max_char: 4000
  delay: 3000
  token_expired: 5
  send_chunk_mode: auto
  send_chunk_mode: auto
  
mssql:
  default:
    host: http://localhost:8001/mssql/api/querytool/
    server: server1

redis:
  host: 127.0.0.1
  port: 6379
  password: null
  db: 15
  ttl: 300
  max_payload_size_kb: 1024